baseUrl = 'https://seung-hun-h.github.io'

theme = 'PaperMod'

languageCode = 'ko-KR'

title = 'ìƒê°í•˜ëŠ” ê°œë°œ'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
env = 'production'
title = 'ìƒê°í•˜ëŠ” ê°œë°œ'
description = 'ë‚˜ì˜ ìƒê°ì„ ë‹´ì€ ê°œë°œ ë¸”ë¡œê·¸'
keywords = ['Blog', 'Tech']
author = 'í•¨ìŠ¹í›ˆ'

[params.homeInfoParams]
Title = 'í•¨ìŠ¹í›ˆ | Software EngineerğŸ’»'
Content = 'í•„ìš”í•œ ê²ƒì„ ì˜ë§Œë“¤ê³  ì‹¶ì€ ì†Œí”„íŠ¸ì›¨ì–´ ì—”ì§€ë‹ˆì–´ì…ë‹ˆë‹¤'

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/seung-hun-h'

[[params.socialIcons]]
name = 'linkedIn'
url = 'https://www.linkedin.com/in/%EC%8A%B9%ED%9B%88-%ED%95%A8-9a0948255?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app'
